ilp_address: test.cuetzpalli
secret_seed: 679261d379ca3a5ed03a130749c07ea9eb32ae3cea96e22911a4bf21a7e64b4e
admin_auth_token: admin.cuetzpalli
database_url: redis://ilp-redis:6379/2
# database_prefix: ilp_
http_bind_address: 0.0.0.0:7770
settlement_api_bind_address: 0.0.0.0:7771
# settlement_after: 0
# default_spsp_account: my_account
# route_broadcast_interval: 30000
# exchange_rate.provider:
#   CryptoCompare: API_KEY
# exchange_rate.poll_interval: 60000
# exchange_rate.spread: 0.01
# prometheus.bind_address: address:port
# prometheus.histogram_window: 300000
# prometheus.histogram_granularity: 10000